// #region Imports

import { ReactNode } from 'react';

import type { Metadata } from 'next';

import { LanguageProvider } from '@/components/language/language-provider';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { cn } from '@/lib/utils';
import { sora } from '@/styles/fonts';

import '@/styles/globals.css';

// #endregion

interface RootLayoutProsp {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: 'Cash In Hand',
  // description: 'Generated by create next app',
};

/**
 * @layout
 * @returns {JSX.Element} The root layout.
 */
export default function RootLayout({ children }: RootLayoutProsp): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-sora antialiased', sora.variable)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <LanguageProvider>{children}</LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
