import { ReactNode } from 'react';

import type { Metadata } from 'next';

import '@/assets/globals.css';

import { ClerkProvider } from '@clerk/nextjs';

import { cn } from '@/lib/utils';

import { geistMono, geistSans } from '@/assets/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className={cn('w-full min-h-screen font-sans antialiased', geistMono.variable, geistSans.variable)}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
